# Generated by Django 4.0.3 on 2022-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('login', models.CharField(max_length=56)),
                ('password', models.CharField(max_length=56)),
            ],
        ),
    ]
