# Generated by Django 4.0.3 on 2022-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='cookies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(default=str, max_length=56),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_action_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='login',
            field=models.CharField(default=str, max_length=56),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='password',
            field=models.CharField(default=str, max_length=56),
        ),
    ]
