version: '3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  bot:
    build:
      context: ./
      dockerfile: Dockerfile.bot
    command: python3 main.py
    depends_on:
      - db


volumes:
  postgres_data:
